# Conda metadata description

package:
  name: ohsu-compbio-viper
  version: "1.12.0"

source:
  git_url: https://github.com/ohsu-comp-bio/viper.git

requirements:
  build:
    - ncurses
    - r
    - r-ggplot2==2.2.1
    - r-reshape==0.8.6
    - r-optparse
    - bioconductor-viper==1.12.0

  run:
    - r
    - r-ggplot2==2.2.1
    - r-reshape==0.8.6
    - r-optparse
    - bioconductor-viper==1.12.0

test:
  commands:

