{% set version = '2.2.1.11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tcr
  version: {{ version|replace("-", "_") }}

source:
  fn: tcR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tcR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tcR/tcR_{{ version }}.tar.gz
  sha256: 0090b2287e950bc8ff36eb2b842b1e3aafd2c66b1a10261e401501b53c97ddf3

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.8), roxygen2 (>= 3.0.0)
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-rcpp >=0.11.1
    - r-data.table >=1.9.0
    - r-dplyr >=0.4.0
    - r-ggplot2 >=1.0.0
    - r-gridextra >=0.9.0
    - r-gtable >=0.1.2
    - r-igraph >=0.7.1
    - r-reshape2 >=1.2.0
    - r-scales >=0.3.0
    - r-stringdist >=0.7.3

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.1
    - r-data.table >=1.9.0
    - r-dplyr >=0.4.0
    - r-ggplot2 >=1.0.0
    - r-gridextra >=0.9.0
    - r-gtable >=0.1.2
    - r-igraph >=0.7.1
    - r-reshape2 >=1.2.0
    - r-scales >=0.3.0
    - r-stringdist >=0.7.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tcR')"           # [not win]
    - "\"%R%\" -e \"library('tcR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://imminfo.github.io/tcr/
  license: Apache License 2.0
  summary: Platform for the advanced analysis of T cell receptor and Immunoglobulin repertoires
    data and visualisation of the analysis results.
  license_family: APACHE

# The original CRAN metadata for this package was:

# Package: tcR
# Type: Package
# Title: Advanced Data Analysis of Immune Receptor Repertoires
# Version: 2.2.1.11
# Date: 2016-04-22
# Author: Vadim Nazarov
# Maintainer: Vadim Nazarov <vdm.nazarov@gmail.com>
# Description: Platform for the advanced analysis of T cell receptor and Immunoglobulin repertoires data and visualisation of the analysis results.
# License: Apache License 2.0
# Depends: R (>= 2.15.1), ggplot2 (>= 1.0.0), dplyr (>= 0.4.0), gridExtra (>= 0.9.0), reshape2 (>= 1.2.0), igraph (>= 0.7.1)
# Imports: utils (>= 3.1.0), Rcpp (>= 0.11.1), grid (>= 3.0.0), data.table (>= 1.9.0), gtable (>= 0.1.2), stringdist (>= 0.7.3), scales (>= 0.3.0)
# Suggests: knitr (>= 1.8), roxygen2 (>= 3.0.0)
# LinkingTo: Rcpp
# URL: http://imminfo.github.io/tcr/
# BugReports: https://github.com/imminfo/tcr/issues
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-04-22 09:23:06 UTC; vdn
# Repository: CRAN
# Date/Publication: 2016-04-22 13:10:15

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
