package:
  name: eurydice
  version: "0.1.0"

source:
  git_rev: v0.1.0 
  git_url: https://github.com/ohsu-comp-bio/eurydice.git 

requirements:
  run:
    - python=3.5
    - pip=10.0.1
    - numpy=1.14
    - pandas=0.23.3
    - pystan=2.17.1
    - scikit-learn=0.19.1
    - scipy=1.1.0
    - dill
    - matplotlib
    - seaborn

test:
    

about:
  home: https://github.com/ohsu-comp-bio/eurydice
  license: MIT
  summary: Eurydice - applying PRECEPTS signatures to SMMART patients
