package:
  name: dryad
  version: 0.2.1rc2

requirements:

  build: 
    - python=3.5
    - pip=10.0.1
    - numpy=1.14.3
    - pandas=0.23.3
    - pystan=2.17.1
    - scikit-learn=0.19.1
    - scipy=1.1.0

  run:
    - python=3.5
    - pip=10.0.1
    - numpy=1.14.3
    - pandas=0.23.3
    - pystan=2.17.1
    - scikit-learn=0.19.1
    - scipy=1.1.0

test:

about:
  home: https://github.com/ohsu-comp-bio/dryad
  license: MIT
  summary: 
