# Conda metadata description for qc
package:
        name: tcr.qc
        version: "1.0.0"

source:
        git_url: https://github.com/ohsu-comp-bio/tcr_sequencing_tools.git

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
        build:
            - r=3.3.2

        run:
            - r=3.3.2
            - r-optparse=1.4.4=r3.3.2_0
            - r-data.table=1.10.4=r3.3.2_0
            - bioconductor-shortread=1.32.0=r3.3.2_0
            - r-openxlsx=4.0.17=r3.3.2_0

test:
        commands:
            - aggregate.qc.R --help
            - galaxy.qc.R --help
