# Conda metadata description for qc
package:
        name: tcr.qc
        version: "1.0.0"

source:
        git_url: https://github.com/ohsu-comp-bio/tcr_sequencing_tools.git

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
        build:
            - r=3.4.1

        run:
            - r=3.4.1
            - r-optparse=1.6.0
	    - r-data.table=1.10.4
	    - bioconductor-shortread=1.36.0
	    - r-xlsx=0.5.7

test:
        commands:
            - galaxy.qc.R --help
	    - aggregate.qc.R --help

