# Conda metadata description
package:
    name: lancet
    version: "1.0.6"

source: 
    git_rev: v1.0.6
    git_url: https://github.com/nygenome/lancet.git

requirements:
    build:
        - make
        - gcc
        - cmake
        - bamtools 2.4.1
        - htslib 1.8

    run:
        - bamtools 2.4.1
        - htslib 1.8

test:
    commands:
        - lancet --help
