{% set version = '1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-writexl
  version: {{ version|replace("-", "_") }}

source:
  fn: writexl_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/writexl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/writexl/writexl_{{ version }}.tar.gz
  sha256: 8e91b06d75584a7d09ea041914003a2222c21ce06b9bfb54c8157fc29a085b64

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spelling, readxl, nycflights13, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('writexl')"           # [not win]
    - "\"%R%\" -e \"library('writexl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/writexl (devel), https://libxlsxwriter.github.io (upstream)
  license: BSD_2_clause + file LICENSE
  summary: Zero-dependency and data frame to xlsx exporter based on 'libxlsxwriter'.  Fast and
    no Java or Excel required.
  license_family: BSD

# The original CRAN metadata for this package was:

# Package: writexl
# Type: Package
# Title: Export Data Frames to Excel 'xlsx' Format
# Version: 1.0
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4035-0289")), person("John McNamara", role = "cph", comment = "Author of libxlsxwriter (see AUTHORS and COPYRIGHT files for details)"))
# Description: Zero-dependency and data frame to xlsx exporter based on 'libxlsxwriter'.  Fast and no Java or Excel required.
# License: BSD_2_clause + file LICENSE
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/ropensci/writexl (devel), https://libxlsxwriter.github.io (upstream)
# BugReports: https://github.com/ropensci/writexl/issues
# RoxygenNote: 6.0.1
# Suggests: spelling, readxl, nycflights13, testthat
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2018-05-10 13:27:52 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>), John McNamara [cph] (Author of libxlsxwriter (see AUTHORS and COPYRIGHT files for details))
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-05-10 14:03:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
