# Conda metadata description for aggregate.qc
package:
        name: tcr.diversity.analysis
        version: "1.0.0"

source:
        git_url: https://github.com/ohsu-comp-bio/tcr_sequencing_tools.git

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
        build:
            - r=3.4.1

        run:
            - r=3.4.1
            - r-data.table=1.10.4
            - r-tcr=2.2.1.11
